### ISSUE TITLE
Spawn codiad container for existing projects

### ISSUE THREAD

**Issue by peter-hartmann** [linuxserver/docker-codiad#10]
This beautiful lightweight ide wrapped into a docker container doesn't easily adapt to an existing dev infrastructure.  It is missing an easy way to spawn a docker-codiad container to manage existing projects.  This should be as easy as mounting an existing projects folder as docker volume.

Is there a reason why this wasn't considered?  Or am I missing something?  Seems to be the natural thing 
to do for a docker container.  Would it be easy easy to add?

Peter

**Comment by tobbenb** [comment]
I'm not sure I understand what the issue is. I haven't used this container, but can't you simply browse to the mounted volume and open your existing project?

**Comment by peter-hartmann** [comment]
@tobbenb the only mountabe volume is 'config'.  There is no easy way to mount existing projects.

**Comment by tobbenb** [comment]
You can mount what you want. Just use the -v option when you create the container.
In codiad you can browse through the the mount point you chose.

**Comment by peter-hartmann** [comment]
The way I understand it - after mounting a folder you'll still need to create a codiad project and then inspect data/projects.php file to see how the pathing is laid out and modify that php file manually.  Or replace the project folder created with codiad with a symlink to your own folder.  However if you have multiple projects this quickly becomes painful.

**Comment by tobbenb** [comment]
I played with codiad a little now and see what you mean. But I don't really see how to make this a one solution fits all.
You either have to copy the files into the correct folders inside /config or edit the config.php. 
Might be better to ask the codiad developers to make an easy export/import function. Might even be a plugin for that already.
I see you can import from a git repo when creating a new project, so that might be the best option.

**Comment by peter-hartmann** [comment]
Agree, ideally codiad would support this better.
This docker container here perhaps could simply start with a pre-configured project where the project folder is a volume that can optionally be mapped to a container folder?
The just-spawn-and-go short setup instructions would make it very attractive for codiad newbies.
