### ISSUE TITLE
Default project dir should be set to `/config/projects`

### ISSUE THREAD

**Issue by zeigerpuppy** [linuxserver/docker-codiad#14]
I am installing docker-codiad on debian9 docker v 17.12.0-ce

I am using docker-compose with the volume mapping
```
      - '/user/codiad_config:/config'
```

The docs suggest using the `/config/projects` folder for the codiad projects but when the codiad container is built, new projects are stored in `/config/www/workspace` by default.

It would be good to change the default in the build config file to allow projects to go the correct `/config/projects` folder.

**Comment by tobbenb** [comment]
It's not possible to set a default path for projects to /config/projects. The reason is that the config uses a base path, which is /config/www/, and Codiad then sets the workspace folder according to the base path.

If you know of a way to set only the projects folder, then please tell.

**Comment by zeigerpuppy** [comment]
yes, I see why that's an issue.  Really all I want to achieve is a single folder that can be mapped for projects rather than the whole `config` folder.
I have tried changing the build script a little to see if I can get it working with a separate workspace folder.
Essentially I just got it to pull to a build folder first and then copy to the `www` folder.  This gets around the git errors thrown in pulling to a folder that already has contents, but strangely results in a codiad install that doesn't seem to show files and gives a spinning wheel on projects.

I have forked the project and my changes are shown here: https://github.com/zeigerpuppy/docker-codiad/blob/master/root/etc/cont-init.d/50-install

**Comment by zeigerpuppy** [comment]
ah, looks like I have hit this issue: https://github.com/Codiad/Codiad/issues/1082
will update the fork and make a pull request when I get it working...

**Comment by sparklyballs** [comment]
that issue on the codiad github page does not appear in any way connected to your "issue"

**Comment by sparklyballs** [comment]
you can volume mount /config/www/workspace to another location if you require to.

**Comment by zeigerpuppy** [comment]
You can't mount the workspace folder because the git clone of codiad fails if the workspace folder is already present (it gets created by docker when the volume mount is created)

**Comment by sparklyballs** [comment]
i've worked out how to set the whitelist folders to allow to use /config/projects as a data folder without the need for glue and string fixes. 

i am testing it currently and will eventually push if it stands up well.
