### ISSUE TITLE
Plugins extension

### ISSUE THREAD

**Issue by wernight** [linuxserver/docker-codiad#2]
Could you add simple documentation on how to add extra plugins, a a bit like PHP extension for official PHP?

PS: I wanted to try mostly the HTML entities and HTML preview plugins in addition to existing ones.

**Comment by wernight** [comment]
Looking at the code it may be simplest to make a helper script in `$PATH` called `docker-codiad-ext-install` like:

```
$PLUGIN_NAME=$1
$PLUGIN_GIT=$2

# TODO: CHeck arguments

if [[ ! -d "/config/www/plugins/$PLUGIN_NAME/.git" ]]; then
    git clone $PLUGIN_GIT $PLUGIN_NAME/
fi

# Did not opt out for autoupdates?
if [ ! "$ADVANCED_DISABLEUPDATES" ]; then
    cd /config/www/plugins/$PLUGIN_NAME/
    git pull
fi

chown -R abc:abc /config/www/plugins/$PLUGIN_NAME/
```

Now users can add plugins by adding files to `/etc/my_init.d/40_some_plugins` with:

```
docker-codiad-ext-install my-name https://...
docker-codiad-ext-install my-name https://...
```

or by directly extracting plugins under `/config/www/plugins/` as UID (TODO: give UID of `abc`).

**Comment by sparklyballs** [comment]
from the README
"We have added a few plugins. More can be added in the marketplace in the WebUI"

**Comment by wernight** [comment]
Once this is done, the default image may actually have no plugin by default or/and offer a tag with none and one with all.
