### ISSUE TITLE
Automatic build

### ISSUE THREAD

**Issue by wernight** [linuxserver/docker-codiad#3]
A few things that shocked more for this repo compared to others of LinuxServer:
- Should be an automated build
- Should point to this GitHub (and this GitHub should probably link back to Docker Hub).

**Comment by sparklyballs** [comment]
automatic builds are the exception rather than the norm, most of our builds are manual builds and are built on our jenkins ci server.
the few that are automatic builds were kept that way to preserve the stats those builds had accumulated.

**Comment by wernight** [comment]
Any reason _not_ to have a trusted automated build?

**Comment by lonix** [comment]
Im also currious about this.

**Comment by wernight** [comment]
It's actually not an issue at all to have it automated, https://hub.docker.com/r/wernight/codiad/

yeah, we know this. we have built dockers before.
a decision was made some time ago to use jenkins to build and push our docker images to the hub.
whether we stay doing that in the future is under review.

**Comment by lonix** [comment]
Good Job !

**Comment by sparklyballs** [comment]
docker automated builds stopped being trusted builds quite a while ago.

**Comment by wernight** [comment]
First time I hear that, must have missed some big news. I don't find any source that Docker hub automated builds may be tempted with by anyone outside Docker. Sure one can commit a weird thing for a short time but then I think Docker hub still shows that build's Dockerfile

**Comment by sparklyballs** [comment]
if i were so inclined , i could write a malicious entrypoint script, build the image on the hub via automated build. temporarily turn off the automated build on the hub. clean my commit history on git. and the users on the hub would be none the wiser because only the dockerfile is shown.

**Comment by wernight** [comment]
I agree it's possible, yet it's harder. Another thing I like to do it avoid entrypoint or scripts when possible. 

Back to the original question, if you prefer to use your own farm I guess that all fine, but then you could actually reduce the image size a lot more using scratch and Docker minifiers.
